[build]
  base = "ilkerkabacik-final"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
